language: php
php:
  - '5.6'
  - '7.0'
  - '7.1'
  - nightly
matrix:
  allow_failures:
  - php: nightly
install:
  - pear install PHP_CodeSniffer
  - phpenv rehash
script:
  - find . -name '*.php' -print0 | xargs -0 -n1 php -lf
  - phpcs --standard=PSR1,PSR2 --extensions=php --ignore="^$(pwd)/ext_scripts/*" . || true # Allow failures for now
